In [9]:
import camelot
tables = camelot.read_pdf('student_attendance.pdf')#, pages='1')
# for table in tables:
#     table.df
tables[0].df

,0,1,2,3,4,5
0,"University of Engineering & Management , Kolka...",,,,,
1,,Section Class Roll,Enrollment\n No.,Registration\n No.,Student Name,% of Attendance
2,A,1,12020009001020,304202000900021 AADRITO ROY,,81.3
3,A,2,12020009028032,304202000900861 ABHIRUP DAS,,50.0
4,A,3,12020009023048,304202000900745 ACHYUT SETH,,32.3
5,A,4,12020009022284,304202000901049 AFREEN ZEB,,49.0
6,A,5,12020009022071,304202000900538 AKASH PAUL,,78.1
7,A,6,12020009029002,304202000900904 AMIYENDRA SARKAR,,40.6
8,A,7,12020009023004,304202000900701 ANIKET NAYEK,,89.6
9,A,8,12020009028059,304202000900888 ANIRBAN GHOSH,,57.3
10,A,9,12020009001318,304202000900317 ANKIT ROY,,22.9
11,A,10,12020009029024,304202000900926 ANOM CHAKRAVORTY,,82.3
12,A,11,12020009022006,304202000900473 ANURAG BAGCHI,,84.4
13,A,12,12020009001228,304202000900228 APRATIM GHOSH,,71.9
14,A,13,12020009023051,304202000900748 ARIJIT BASAK,,92.7
15,A,14,12020009022132,304202000900599 ARITRA GHOSH,,25.0
16,A,15,12020009001080,304202000900081 ARKOPRABHO DAS,,75.0
17,A,16,12020009022278,304202000901029 ARYA SINGH,,83.3
18,A,17,12020009022133,304202000900600 AVHIRUP MONDAL,,83.3
19,A,18,12020009022063,304202000900530 AYAN PAUL,,12.5
20,A,19,12020009022016,304202000900483 BASABPRIYO BHATTACHARJEE,,83.3
21,A,20,12020009023102,304202000900799 CHANDAN KUMAR,,89.6
22,A,21,12020009022051,304202000900518 DEBARGHYA KAYAL,,53.1
23,A,22,12020009022052,304202000900519 DEBOLINA MITRA,,88.5
24,A,23,12020009022095,304202000900562 DIKSHA BUXANI,,85.4
25,A,24,12020009022053,304202000900520 GOPESH GOSWAMI,,38.5
26,A,25,12020009022025,304202000900492 INDRAJIT SINHA,,10.4
27,A,26,12020009029008,304202000900910 JYOTIRMOY ROY,,91.7
28,A,27,12020009001275,304202000900275 KOUSHIK DHAR,,55.2
29,A,28,12020009023087,304202000900784 KUNAL SEN,,75.0
30,A,29,12020009023072,304202000900769 MAHFUZ AHMED,,91.7
31,A,30,12020009022253,304202000901004 MD SAHIN,,58.3
32,A,31,12020009023120,304202000901032 MEGHA GHOSH,,81.3
33,A,32,12020009027006,304202000900825 MONJIMA LAHIRI,,78.1
34,A,33,12020009029061,304202000900963 NAMRATA SINGH,,28.1
35,A,34,12020009022285,304202000901050 NILADRI DATTA,,10.4
36,A,35,12020009028064,304202000900893 NIRMALYA DAS,,59.4
37,A,36,12020009022234,304202000900694 PIYUSH RAJ,,78.1
38,A,37,12020009022191,304202000900658 PRINCE KUMAR SINGH,,9.4
39,A,38,12020009027007,304202000900826 PRIYANGSU MONDAL,,70.8
40,A,39,12020009022193,304202000900660 RAHUL MONDAL,,74.0
41,A,40,12020009022057,304202000900524 RAJESH MANDAL,,61.5
42,A,41,12020009022244,304202000900995 RAUNAK SARKAR,,43.8
43,A,42,12020009022108,304202000900575 RISHIN CHAUDHURY,,24.0
44,A,43,12020009022270,304202000901021 RITU DHAR,,58.3
45,A,44,12020009022061,304202000900528 ROHIT ROY,,77.1